version: '3.3'
services:
  app:
    environment:
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www

  db:
    environment:
      MYSQL_DATABASE: choice
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev

  webserver:
    volumes:
      - ./:/var/www
