version: '3.3'
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: drewpayment/cmp-app:latest
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - app-network
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  #Nginx Service
  webserver:
    image: drewpayment/cmp-web:latest
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - '80:80'
      - '443:443'
    networks:
      - app-network
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

  #MySQL Service
  db:
    # image: mysql:5.7.22
    image: drewpayment/cmp-db:latest
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: choice
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
