/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Decimal = ColumnType<string, number | string>;

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Comments {
  active: number;
  body: string;
  created_at: Date | null;
  from_user: Generated<number>;
  id: Generated<number>;
  on_post: Generated<number>;
  updated_at: Date | null;
}

export interface CompanyOptions {
  created_at: Date | null;
  has_paystub_notifications: number;
  id: Generated<number>;
  updated_at: Date | null;
}

export interface Documents {
  created_at: Date | null;
  description: string;
  file_path: string;
  id: Generated<number>;
  mime_type: string;
  name: string;
  updated_at: Date | null;
  uploaded_by: string;
}

export interface DocumentFiles {
  id: Generated<number>;
  name: string;
  description: string | null;
  original_filename: string;
  storage_type: "vercel_blob";
  blob_url: string;
  blob_pathname: string;
  download_url: string | null;
  mime_type: string;
  file_size: number;
  uploaded_by: string;
  upload_ip: string | null;
  tags: string | null; // JSON
  metadata: string | null; // JSON
  status: "uploading" | "active" | "archived" | "deleted";
  created_at: Date | null;
  updated_at: Date | null;
}

export interface EmployeeInvoice {
  employee_id: number;
  invoice_id: number;
}

export interface EmployeePermission {
  employee_id: number;
  permission_id: number;
}

export interface Employees {
  address: string;
  address_2: string | null;
  city: string | null;
  country: string | null;
  created_at: Date | null;
  deleted_at: Date | null;
  email: string;
  has_been_fixed: Generated<number>;
  hidden_payroll: Generated<number>;
  id: Generated<number>;
  is_active: number;
  is_admin: Generated<number>;
  is_mgr: Generated<number>;
  name: string;
  phone_no: string | null;
  postal_code: string | null;
  sales_id1: Generated<string>;
  sales_id2: Generated<string>;
  sales_id3: Generated<string>;
  state: string | null;
  updated_at: Date | null;
}

export interface EmployeeUser {
  employee_id: number;
  user_id: number;
}

export interface Expenses {
  agentid: number;
  amount: Generated<Decimal>;
  created_at: Date | null;
  expid: Generated<number>;
  issue_date: Date;
  notes: string;
  type: string;
  updated_at: Date | null;
  vendor_id: Generated<number>;
  wkending: Date;
}

export interface Invoices {
  address: string;
  agentid: number;
  amount: Generated<string>;
  city: string;
  created_at: Date | null;
  first_name: string;
  invoice_id: Generated<number>;
  issue_date: Date;
  last_name: string;
  sale_date: Date;
  status: string;
  updated_at: Date | null;
  vendor: string;
  wkending: Date;
}

export interface Jobs {
  attempts: number;
  available_at: number;
  created_at: number;
  id: Generated<number>;
  payload: string;
  queue: string;
  reserved_at: number | null;
}

export interface Links {
  created_at: Date | null;
  id: Generated<number>;
  name: string;
  updated_at: Date | null;
}

export interface ManagerEmployees {
  created_at: Date | null;
  employee_id: number;
  id: Generated<number>;
  manager_id: number;
  updated_at: Date | null;
}

export interface Migrations {
  batch: number;
  migration: string;
}

export interface OauthAccessTokens {
  client_id: number;
  created_at: Date | null;
  expires_at: Date | null;
  id: string;
  name: string | null;
  revoked: number;
  scopes: string | null;
  updated_at: Date | null;
  user_id: number | null;
}

export interface OauthAuthCodes {
  client_id: number;
  expires_at: Date | null;
  id: string;
  revoked: number;
  scopes: string | null;
  user_id: number;
}

export interface OauthClients {
  created_at: Date | null;
  id: Generated<number>;
  name: string;
  password_client: number;
  personal_access_client: number;
  redirect: string;
  revoked: number;
  secret: string | null;
  updated_at: Date | null;
  user_id: number | null;
}

export interface OauthPersonalAccessClients {
  client_id: number;
  created_at: Date | null;
  id: Generated<number>;
  updated_at: Date | null;
}

export interface OauthRefreshTokens {
  access_token_id: string;
  expires_at: Date | null;
  id: string;
  revoked: number;
}

export interface Overrides {
  agentid: number;
  commission: Generated<Decimal>;
  created_at: Date | null;
  issue_date: Date;
  name: string;
  ovrid: Generated<number>;
  sales: number;
  total: Generated<Decimal>;
  updated_at: Date | null;
  vendor_id: Generated<number>;
  wkending: Date;
}

export interface PasswordResets {
  created_at: Generated<Date>;
  email: string;
  token: string;
}

export interface Payroll {
  agent_id: number;
  agent_name: string;
  amount: Generated<Decimal>;
  created_at: Date | null;
  id: Generated<number>;
  is_paid: number;
  pay_date: Date;
  updated_at: Date | null;
  vendor_id: Generated<number>;
}

export interface PayrollRestriction {
  created_at: Date | null;
  hour: number;
  id: Generated<number>;
  minute: number;
  modified_by: number;
  updated_at: Date | null;
}

export interface Paystubs {
  agent_id: number;
  agent_name: string;
  amount: Generated<Decimal>;
  created_at: Date | null;
  id: Generated<number>;
  issue_date: Date;
  modified_by: number;
  updated_at: Date | null;
  vendor_id: number;
  vendor_name: string;
  weekend_date: Date;
}

export interface Permissions {
  created_at: Date | null;
  emp_id: number;
  id: Generated<number>;
  is_active: number;
  updated_at: Date | null;
}

export interface PersonalAccessTokens {
  abilities: string | null;
  created_at: Date | null;
  id: Generated<number>;
  last_used_at: Date | null;
  name: string;
  token: string;
  tokenable_id: number;
  tokenable_type: string;
  updated_at: Date | null;
}

export interface Posts {
  active: number;
  author_id: Generated<number>;
  body: string;
  created_at: Date | null;
  id: Generated<number>;
  slug: string;
  title: string;
  updated_at: Date | null;
}

export interface TaggingTagged {
  id: Generated<number>;
  tag_name: string;
  tag_slug: string;
  taggable_id: number;
  taggable_type: string;
}

export interface TaggingTagGroups {
  id: Generated<number>;
  name: string;
  slug: string;
}

export interface TaggingTags {
  count: Generated<number>;
  id: Generated<number>;
  name: string;
  slug: string;
  suggest: Generated<number>;
  tag_group_id: number | null;
}

export interface Testimonials {
  content: string;
  created_at: Date | null;
  id: Generated<number>;
  location: string;
  testimonial_type: number;
  updated_at: Date | null;
}

export interface TestimonialTypes {
  created_at: Date | null;
  id: Generated<number>;
  name: string;
  type: number;
  updated_at: Date | null;
}

export interface UserNotifications {
  created_at: Date | null;
  employee_id: number;
  has_paystub_notifier: Generated<number>;
  id: Generated<number>;
  notifier_destination: string | null;
  paystub_notifier_type: number | null;
  updated_at: Date | null;
  user_id: number;
}

export interface Users {
  created_at: Date | null;
  deleted_at: Date | null;
  email: string;
  id: number;
  name: string;
  password: string;
  remember_token: string | null;
  role: Generated<"admin" | "author" | "subscriber">;
  uid: Generated<number>;
  updated_at: Date | null;
}

export interface Vendors {
  created_at: Date | null;
  id: Generated<number>;
  is_active: number;
  name: string;
  updated_at: Date | null;
}

export interface DB {
  comments: Comments;
  company_options: CompanyOptions;
  document_files: DocumentFiles;
  documents: Documents;
  employee_invoice: EmployeeInvoice;
  employee_permission: EmployeePermission;
  employee_user: EmployeeUser;
  employees: Employees;
  expenses: Expenses;
  invoices: Invoices;
  jobs: Jobs;
  links: Links;
  manager_employees: ManagerEmployees;
  migrations: Migrations;
  oauth_access_tokens: OauthAccessTokens;
  oauth_auth_codes: OauthAuthCodes;
  oauth_clients: OauthClients;
  oauth_personal_access_clients: OauthPersonalAccessClients;
  oauth_refresh_tokens: OauthRefreshTokens;
  overrides: Overrides;
  password_resets: PasswordResets;
  payroll: Payroll;
  payroll_restriction: PayrollRestriction;
  paystubs: Paystubs;
  permissions: Permissions;
  personal_access_tokens: PersonalAccessTokens;
  posts: Posts;
  tagging_tag_groups: TaggingTagGroups;
  tagging_tagged: TaggingTagged;
  tagging_tags: TaggingTags;
  testimonial_types: TestimonialTypes;
  testimonials: Testimonials;
  user_notifications: UserNotifications;
  users: Users;
  vendors: Vendors;
}
